Add files via upload

diff --git a/.github/workflows/高通410 immortalwrt.yml b/.github/workflows/高通410 immortalwrt.yml
--- a/.github/workflows/高通410 immortalwrt.yml
+++ b/.github/workflows/高通410 immortalwrt.yml
@@ -66,9 +66,19 @@ jobs:
       run: |
         sudo -E apt-get -y update
         sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/depend_ubuntu2204_openwrt)
-        sudo wget -O /usr/local/bin/mkbootimg https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/refs/heads/main/mkbootimg
-        sudo chmod +x /usr/local/bin/mkbootimg
-        file /usr/local/bin/mkbootimg
+        wget https://raw.githubusercontent.com/xuxin1955/depend_ubuntu2204_openwrt/main/mkbootimg_10.0.0+r36-9_all.deb
+        sudo dpkg -i mkbootimg_10.0.0+r36-9_all.deb
+        sudo apt-get install -f -y
+        # 验证安装
+        mkbootimg --help || true
+        MKBOOTIMG_PATH=$(which mkbootimg)
+        if [ -n "$MKBOOTIMG_PATH" ]; then
+        echo "mkbootimg found at: $MKBOOTIMG_PATH"
+        file "$MKBOOTIMG_PATH"
+        else
+        echo "❌ mkbootimg not found in PATH!"
+        fi
+
         sudo timedatectl set-timezone "$TZ"
         sudo chmod 777 /mnt
         df -hT
